# Generated by Django 3.2.8 on 2021-10-08 14:57

from django.db import migrations


groups = {
    'regular': [
        'view_contact',
    ],
    'admin': [
        'view_contact',
        'add_contact',
        'change_contact',
    ],
    'superuser': [
        'view_contact',
        'add_contact',
        'change_contact',
        'delete_contact',
    ],
}


def create_user_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    known_permissions = {}

    for group_name, permissions in groups.items():
        group = Group(name=group_name)
        group.save()

        for permission_name in permissions:
            if permission_name not in known_permissions:
                known_permissions[permission_name] = Permission.objects\
                    .get(codename=permission_name)
            group.permissions.add(known_permissions[permission_name])
        group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_user_groups, migrations.RunPython.noop, atomic=True)
    ]
